// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAtxW7w38pkVuHxXIY8kgmr7zER3TmJ0',
    appId: '1:1084429409780:web:35c4e80ccc5d93332b2da1',
    messagingSenderId: '1084429409780',
    projectId: 'price-negotiator-83846',
    authDomain: 'price-negotiator-83846.firebaseapp.com',
    databaseURL: 'https://price-negotiator-83846-default-rtdb.firebaseio.com',
    storageBucket: 'price-negotiator-83846.firebasestorage.app',
    measurementId: 'G-MMP06E3J6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPZGLD0GIR2u4fNKIRVNIRkyuy7Mcc4s',
    appId: '1:1084429409780:android:8979a83bda952ef72b2da1',
    messagingSenderId: '1084429409780',
    projectId: 'price-negotiator-83846',
    databaseURL: 'https://price-negotiator-83846-default-rtdb.firebaseio.com',
    storageBucket: 'price-negotiator-83846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrDmEEIuN6pa_oY_ai3w_R3RCipxDPUI',
    appId: '1:1084429409780:ios:69386006a5ba09af2b2da1',
    messagingSenderId: '1084429409780',
    projectId: 'price-negotiator-83846',
    databaseURL: 'https://price-negotiator-83846-default-rtdb.firebaseio.com',
    storageBucket: 'price-negotiator-83846.firebasestorage.app',
    iosBundleId: 'com.example.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOrDmEEIuN6pa_oY_ai3w_R3RCipxDPUI',
    appId: '1:1084429409780:ios:69386006a5ba09af2b2da1',
    messagingSenderId: '1084429409780',
    projectId: 'price-negotiator-83846',
    databaseURL: 'https://price-negotiator-83846-default-rtdb.firebaseio.com',
    storageBucket: 'price-negotiator-83846.firebasestorage.app',
    iosBundleId: 'com.example.webrtc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIAtxW7w38pkVuHxXIY8kgmr7zER3TmJ0',
    appId: '1:1084429409780:web:01f84d9a8b6a90e42b2da1',
    messagingSenderId: '1084429409780',
    projectId: 'price-negotiator-83846',
    authDomain: 'price-negotiator-83846.firebaseapp.com',
    databaseURL: 'https://price-negotiator-83846-default-rtdb.firebaseio.com',
    storageBucket: 'price-negotiator-83846.firebasestorage.app',
    measurementId: 'G-GEXXNEN5GR',
  );
}
